[build]
  command = "task build-prod"
  functions = "functions"
  publish = "cmd/gateway/nextjs/dist"

[build.environment]
  GO_IMPORT_PATH = "github.com/frankmeza/netlify-go"
  GO111MODULE = "on"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/gateway/:splat"
  status = 200
