# @prettier
# this is for local development,
# netlify.toml handles all netlify tasks
version: "3"

tasks:
  client:
    dir: cmd/gateway/nextjs
    cmds:
      - yarn run dev

  client-export:
    dir: cmd/gateway/nextjs
    cmds:
      - yarn run build

  health:
    dir: cmd/gateway
    cmds:
      - curl localhost:3333/health

  server:
    dir: cmd/gateway
    cmds:
      - go run main.go -dev 1
# run `task server` in one window,
# run `task client` in another,
# then go to localhost:3000
