# this is for local development,
# netlify.toml handles all netlify tasks
version: '3'

tasks:
  server:
    dir: cmd/gateway
    cmds:
      - go run main.go -dev 1

  health:
    dir: cmd/gateway
    cmds:
      - curl localhost:3333/health

  client:
    dir: cmd/gateway/nextjs
    cmds:
      - yarn run dev

  client-export:
    dir: cmd/gateway/nextjs
    cmds:
      - yarn run build
